version: "3"
services:
  basebox.20:
    build:
      context: .
      dockerfile: Dockerfile.20
    image: pwnbox:base.20

  basebox.18:
    build:
      context: .
      dockerfile: Dockerfile.18
    image: pwnbox:base.18

  basebox.16:
    build:
      context: .
      dockerfile: Dockerfile.16
    image: pwnbox:base.16

  ctf:
    build:
      context: .
      args:
        BASE: base.${PWNBOX_BASE}
      dockerfile: Dockerfile.run
    image: pwnbox:runtime.${PWNBOX_BASE}
    depends_on:
      - basebox.${PWNBOX_BASE}
    cap_add:
      - SYS_MODULE
      - SYS_PTRACE
      # - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/Workspace/glibc-all-in-one/libs:/opt/glibc:ro
      - ~/Desktop/CTF/pwn:/pwn
      - ~/Workspace/ctf-challenges/pwn:/ctf-challenges
    network_mode: bridge
    stdin_open: true
    tty: true

  vscode:
    image: pwnbox:vscode.${PWNBOX_BASE}
    cap_add:
      - SYS_MODULE
      - SYS_PTRACE
      # - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/Workspace/glibc-all-in-one/libs:/opt/glibc:ro
      - ~/Desktop/CTF/pwn:/pwn
      - ~/Workspace/ctf-challenges/pwn:/ctf-challenges
    network_mode: bridge
    stdin_open: true
    tty: true
