version: "3"
services:
  ctf:
    image: pwnbox:18.vscode
    cap_drop:
      - SYS_PTRACE
      # - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/Workspace/glibc-all-in-one/libs:/opt/glibc:ro
      - ~/Desktop/CTF/pwn:/pwn
      - ~/Workspace/ctf-challenges/pwn:/ctf-challenges
    network_mode: bridge
    stdin_open: true
    tty: true
