version: "3"
services:
  ctf:
    image: kevin2s/pwnbox:runtime.${PWNBOX_BASE}
    cap_add:
      - SYS_MODULE
      - SYS_PTRACE
      # - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/Workspace/glibc-all-in-one/libs:/opt/glibc:ro
      - ~/Desktop/CTF/pwn:/pwn
      - ~/Workspace/ctf-challenges:/ctf-challenges
    network_mode: bridge
    stdin_open: true
    tty: true

  vscode:
    image: pwnbox:vscode.${PWNBOX_BASE}
    cap_add:
      - SYS_MODULE
      - SYS_PTRACE
      # - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/Workspace/glibc-all-in-one/libs:/opt/glibc:ro
      - ~/Desktop/CTF/pwn:/pwn
      - ~/Workspace/ctf-challenges:/ctf-challenges
    network_mode: bridge
    stdin_open: true
    tty: true
