FROM ubuntu:bionic

# install necessary packages
RUN export DEBIAN_FRONTEND=noninteractive \
    && dpkg --add-architecture i386 && apt-get update && apt-get install -y \
    # debug tools
    man-db build-essential jq strace ltrace gcc gcc-multilib cmake bison flex \
    # gdb
    gdb gdb-multiarch gdbserver glibc-source \
    # debug info
    libc6-dbg libc6-dbg:i386 libc6-dev libc6-dev:i386 \
    # python and related header
    python python-dev python-pip python-setuptools \
    python3 python3-dev python3-pip python3-setuptools \
    libssl-dev libffi-dev \
    # various tools
    wget curl socat netcat iproute2 iputils-ping net-tools nasm upx-ucl ufw \
    autoconf automake libtool nmap openvpn smbclient dnsutils \
    ruby ruby-dev zsh vim tmux git \
    #
    # untar glibc source code
    && cd /usr/src/glibc/ && tar xf glibc-2.27.tar.xz && rm -rf glibc-2.27.tar.xz \
    #
    # clean up
    && apt-get autoremove -y && apt-get clean -y \
    ; rm -rf ~/.cache \
    ; rm -rf /tmp/* \
    ; rm -rf /var/tmp/*

# various tools for pwn
RUN pip3 install -U --no-cache-dir pip \
    && pip2 install -U --no-cache-dir pip \
    #
    && git clone https://github.com/pwndbg/pwndbg.git /usr/local/pwndbg \
    && cd /usr/local/pwndbg && ./setup.sh \
    && wget -O /usr/local/gef.py https://github.com/hugsy/gef/raw/master/gef.py \
    && echo "# source /usr/local/gef.py" >> ~/.gdbinit \
    # split view of pwndbg
    && git clone https://github.com/jerdna-regeiz/splitmind /usr/local/splitmind \
    # pwntools
    && python2 -m pip install -U --no-cache-dir pwntools \
    && python3 -m pip install -U --no-cache-dir pwntools \
    # python/ruby packages & gdb-plugin
    && python3 -m pip install -U --no-cache-dir ropgadget ancypatch swpwn r2pipe \
    && python2 -m pip install -U --no-cache-dir ropgadget ancypatch swpwn r2pipe \
    && gem install one_gadget seccomp-tools \
    # other python panckages
    && python3 -m pip install -U --no-cache-dir pylint ipython yapf impacket z3-solver \
    && python2 -m pip install -U --no-cache-dir pylint ipython yapf impacket z3-solver \
    # patchelf
    && git clone https://github.com/NixOS/patchelf.git /usr/local/patchelf \
    && cd /usr/local/patchelf && ./bootstrap.sh && ./configure \
    && make && make install \
    # reversing tools
    && git clone https://github.com/radareorg/radare2.git /usr/local/radare2 \
    && cd /usr/local/radare2 && ./sys/install.sh \
    #
    # clean up
    && apt-get autoremove -y && apt-get clean -y \
    ; rm -rf ~/.cache \
    ; rm -rf /tmp/* \
    ; rm -rf /var/tmp/*

# prezto
RUN git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" \
    && chsh -s /bin/zsh
COPY .tmux.conf .p10k.zsh .gdbinit /root/
COPY zprezto/ /root/.zprezto/runcoms/
RUN ["/bin/zsh", "-c", "setopt EXTENDED_GLOB; for rcfile in ${ZDOTDIR:-$HOME}/.zprezto/runcoms/^README.md(.N); do ln -s $rcfile ${ZDOTDIR:-$HOME}/.${rcfile:t}; done"]


ENV LANG C.UTF-8
CMD ["zsh"]
