FROM ubuntu:bionic

# install necessary packages
RUN export DEBIAN_FRONTEND=noninteractive \
    && dpkg --add-architecture i386 \
    && apt-get update && apt-get install --no-install-recommends -y \
    # building tools
    build-essential binutils coreutils cmake gcc gcc-multilib bison flex upx-ucl \
    autoconf automake libtool pax-utils \
    # debug
    gdb gdb-multiarch gdbserver glibc-source strace ltrace \
    libc6-dbg libc6-dbg:i386 libc6-dev libc6-dev:i386 \
    # python and related header
    python python-dev python-pip python-setuptools python-wheel \
    python3 python3-dev python3-pip python3-setuptools python3-wheel \
    libssl-dev libffi-dev \
    ruby ruby-dev \
    # other tools
    wget curl vim git > /dev/null \
    # untar glibc source code
    && cd /usr/src/glibc/ && tar xf glibc-2.27.tar.xz && rm -rf glibc-2.27.tar.xz \
    #
    && python3 -m pip install -q -U --no-cache-dir pip \
    && python2 -m pip install -q -U --no-cache-dir pip \
    # pwndbg & gef
    && git clone https://github.com/pwndbg/pwndbg.git /opt/pwndbg \
    && cd /opt/pwndbg && ./setup.sh \
    && curl -fLo /opt/gef.py https://tinyurl.com/gef-master \
    && echo "# source /opt/gef.py" >> ~/.gdbinit \
    # pwntools, ropgadget
    # remove duplicate unicorn==1.0.1
    && python3 -m pip uninstall -y unicorn \
    && python2 -m pip uninstall -y unicorn \
    && python3 -m pip install -q -U --no-cache-dir pwntools ropgadget \
    && python2 -m pip install -q -U --no-cache-dir pwntools ropgadget \
    && gem install one_gadget seccomp-tools \
    # clean up
    && apt-get autoremove -y --purge && apt-get autoclean -y \
    ; rm -rf ~/.cache \
    ; rm -rf /var/lib/apt/lists/* \
    ; rm -rf /tmp/* \
    ; rm -rf /var/tmp/*

ENV LANG C.UTF-8
